### ISSUE TITLE
How does the ('www',3) case equal 0.56? 

### ISSUE THREAD

**Issue by cooknl** [CheckiO-Missions/checkio-task-box-probability#3]
I've been working on this through Empire of Code.

I've got a recursion that goes down every branch of the probability tree, and I've checked it against a hand-written example. I can't find how ('www',3) equals 0.56.

**Comment by Bryukh** [comment]
https://checkio.s3.amazonaws.com/comments/attachments/box-probability-formula.pdf

**Comment by Bryukh** [comment]
https://www.checkio.org/mission/box-probability/

**Comment by cooknl** [comment]
Thank you, I'll look at these.
