### ISSUE TITLE
message ErrUchIsDown

### ISSUE THREAD

**Issue by IvanShkarbut** [CheckiO-Missions/checkio-task-box-probability#5]
my decision to pass the first tests but on 6 test results ErrUchIsDown
[perls.py.zip](https://github.com/CheckiO-Missions/checkio-task-box-probability/files/357959/perls.py.zip)

**Comment by oduvan** [comment]
This is a problem of long running solutions.

It is not a problem this challenge it is CheckiO problem. It will be solved in a coming release.

Thank you
